# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = []
description = "Starter for Remix JavaScript framework"
language = "javascript"
manifest_version = 2
name = "Starter for Remix JavaScript framework"
service_id = ""

[scripts]
build = "npm run build"
post_init = "npm install"
